package br.com.recatalog.B3DataAutomation.pages;

import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import br.com.recatalog.B3DataAutomation.base.BasePage;

public class NotFoundLink extends BasePage {

	public NotFoundLink() {
		super();
	}

	public void downloadNegociosByStockUntilNow(List<String> stockCodes, String data) {
		driver.switchTo().defaultContent(); 
		driver.switchTo().frame("bvmf_iframe");
		
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		
		WebElement dataEl = driver.findElement(By.xpath("//div[@class='DayPickerInput']/input"));
		dataEl.sendKeys(Keys.CONTROL + "a");
		dataEl.sendKeys(Keys.DELETE);
		dataEl.sendKeys(data);
		dataEl.sendKeys(Keys.ENTER);
		
		Instant previous = Instant.now();

		WebElement stockCodeEl = null;
		WebElement pesquisarBtn = null;
//		WebElement ativoPesquisadoLink = null;
		
		for(String code : stockCodes) {
	        JavascriptExecutor js = (JavascriptExecutor) driver;
	        
			stockCodeEl = driver.findElement(By.cssSelector("input[type='text']"));
//			previous = Instant.now();
			stockCodeEl.sendKeys(Keys.CONTROL + "a");
			stockCodeEl.sendKeys(Keys.DELETE);
			stockCodeEl.sendKeys(code);
			stockCodeEl.sendKeys(Keys.ENTER);

			WebDriverWait wait0 = new WebDriverWait(driver, 120);

			wait0.ignoring(StaleElementReferenceException.class)
			.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@type='submit' and @class='button expand']")));
			pesquisarBtn = driver.findElement(By.xpath("//input[@type='submit' and @class='button expand']"));
			js.executeScript("arguments[0].click()", pesquisarBtn);

			try {
				Thread.sleep(1800);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			WebDriverWait wait = new WebDriverWait(driver, 120);

			WebElement el1 = wait.ignoring(StaleElementReferenceException.class)
			.until(ExpectedConditions.presenceOfElementLocated(By.xpath("(//a[contains(text(),'Ativo pesquisado')] | //h3[@id='label-nao-encontrado'])[last()]")));

			System.out.println(el1.getTagName() + " - " + code);

			
//			try {
//			WebElement el = driver.findElement(By.xpath("(//a[contains(text(),'Ativo pesquisado')] | //h3[@id='label-nao-encontrado'])[1]"));
//			System.out.println(el.getTagName() + " - " + code);
//			} catch (StaleElementReferenceException e) {
//				System.out.println(code);
//				continue;
//			}
/*			try {
				String var = "//a[contains(@href,'" + code + "')]";
				List<WebElement> ativoPesquisadoLinks = driver.findElements(By.xpath(var));
				if(ativoPesquisadoLinks.isEmpty()) {
					System.out.println("Sem processamento até o momento: " + code  );
					continue;
				}
				
				ativoPesquisadoLink = ativoPesquisadoLinks.get(0);

				ativoPesquisadoLink.click();
			} catch(NoSuchElementException e) {
				System.out.println("Erro: Sem processamento para a ação: " + code  );
				continue;
			} 
			
			 * catch(StaleElementReferenceException e) {
			 * System.out.println("Erro: StaleElementReferenceException: " + code );
			 * continue; }
			  catch(TimeoutException e) {
				System.err.println("TimeoutException ");
				e.printStackTrace();
				break;
			}catch (ElementClickInterceptedException e) {
				e.printStackTrace();
				continue;
			}
			System.out.println("Code : " + code + " " + ChronoUnit.MILLIS.between(previous,Instant.now()));
*/		}
		
		Instant current =  Instant.now();
		
		long d =  Duration.between(previous, current).getSeconds();
		
		int m = (int) (d/60);
		int s = (int) (d%60);
		
		
		System.out.println("Elapsed Time: " + Duration.between(previous, current).getSeconds());  
		System.out.println("Elapsed Time: " +  m + "m" + s +  "s");  

//		driver.close();
//		driver.quit();
	}

	public static void main(String[] args) {
		NotFoundLink cot = new NotFoundLink();
		cot.initialization("CHROME",
				"http://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/cotacoes/cotacoes");
		List<String> codes = Arrays.asList(
				"ADHM3",
				"TIET11",
				"TIET3",
				"TIET4",
				"AFLT3",
				"RPAD3",
				"RPAD5",
				"RPAD6",
				"ALSO3",
				"ALPK3",
				"ALPA3",
				"ALPA4",
				"APER3",
				"ALUP11",
				"ALUP3",
				"ALUP4",
				"ABEV3",
				"AMBP3",
				"CBEE3",
				"ANIM3",
				"ARZZ3",
				"CRFB3",
				"ATOM3",
				"AZEV3",
				"AZEV4",
				"AZUL4",
				"BTOW3",
				"B3SA3",
				"BAHI3",
				"BMGB4",
				"BIDI11",
				"BIDI3",
				"BIDI4",
				"BEES3",
				"BEES4",
				"BDLL3",
				"BDLL4",
				"BTTL3",
				"BALM3",
				"BALM4",
				"BBSE3",
				"BBML3",
				"ABCB4",
				"BRIV3",
				"BRIV4",
				"BAZA3",
				"BBDC3",
				"BBDC4",
				"BBAS11",
				"BBAS3",
				"BPAC11",
				"BPAC3",
				"BPAC5",
				"BGIP3",
				"BGIP4",
				"BPAR3",
				"BRSR3",
				"BRSR5",
				"BRSR6",
				"IDVL3",
				"IDVL4",
				"BMIN3",
				"BMIN4",
				"BMEB3",
				"BMEB4",
				"BNBR3",
				"BPAN4",
				"PINE3",
				"PINE4",
				"SANB11",
				"SANB3",
				"SANB4",
				"BMKS3",
				"BIOM3",
				"BSEV3",
				"BKBR3",
				"BOBR3",
				"BOBR4",
				"BRML3",
				"BRPR3",
				"BRAP3",
				"BRAP4",
				"BBRK3",
				"AGRO3",
				"BRKM3",
				"BRKM5",
				"BRKM6",
				"BSLI3",
				"BSLI4",
				"BRFS3",
				"BRQB3",
				"CAMB3",
				"CAML3",
				"CCRO3",
				"CEAB3",
				"MAPT3",
				"MAPT4",
				"ELET3",
				"ELET5",
				"ELET6",
				"CLSC3",
				"CLSC4",
				"AALR3",
				"CESP3",
				"CESP5",
				"CESP6",
				"PCAR3",
				"CASN3",
				"CASN4",
				"GPAR3",
				"CEGR3",
				"CEEB3",
				"CEEB5",
				"CEEB6",
				"CEBR3",
				"CEBR5",
				"CEBR6",
				"CMIG3",
				"CMIG4",
				"CEPE3",
				"CEPE5",
				"CEPE6",
				"COCE3",
				"COCE5",
				"COCE6",
				"CSRN3",
				"CSRN5",
				"CSRN6",
				"CEED3",
				"CEED4",
				"EEEL3",
				"EEEL4",
				"FESA3",
				"FESA4",
				"CEDO3",
				"CEDO4",
				"CGAS3",
				"CGAS5",
				"HBTS3",
				"HBTS5",
				"HBTS6",
				"HGTX3",
				"CATA3",
				"CATA4",
				"LCAM3",
				"MSPA3",
				"MSPA4",
				"CPLE3",
				"CPLE5",
				"CPLE6",
				"PEAB3",
				"PEAB4",
				"SBSP3",
				"CSMG3",
				"SAPR11",
				"SAPR3",
				"SAPR4",
				"CSAB3",
				"CSAB4",
				"CSNA3",
				"CTNM3",
				"CTNM4",
				"CTSA3",
				"CTSA4",
				"CTSA8",
				"CIEL3",
				"CMSA3",
				"CMSA4",
				"CNSY3",
				"COGN3",
				"ODER3",
				"ODER4",
				"BRGE11",
				"BRGE3",
				"BRGE5",
				"BRGE6",
				"BRGE7",
				"BRGE8",
				"CALI3",
				"CALI4",
				"TEND3",
				"CORR3",
				"CORR4",
				"RLOG3",
				"CSAN3",
				"CPFE3",
				"CRDE3",
				"CARD3",
				"CTCA3",
				"TRPL3",
				"TRPL4",
				"CVCB3",
				"CYRE3",
				"CCPR3",
				"DMVF3",
				"DASA3",
				"PNVL3",
				"PNVL4",
				"DIRR3",
				"DOHL3",
				"DOHL4",
				"DMMO3",
				"DTCY3",
				"DTCY4",
				"DTEX3",
				"ECOR3",
				"ENBR3",
				"EALT3",
				"EALT4",
				"EKTR3",
				"EKTR4",
				"LIPR3",
				"EMAE3",
				"EMAE4",
				"EMBR3",
				"ECPR3",
				"ECPR4",
				"ENAT3",
				"ENMT3",
				"ENMT4",
				"ENGI11",
				"ENGI3",
				"ENGI4",
				"ENEV3",
				"EGIE3",
				"EQTL3",
				"EQPA3",
				"EQPA5",
				"EQPA6",
				"EQPA7",
				"ETER3",
				"EUCA3",
				"EUCA4",
				"EVEN3",
				"BAUH3",
				"BAUH4",
				"EZTC3",
				"VSPT3",
				"VSPT4",
				"FHER3",
				"CRIV3",
				"CRIV4",
				"FNCN3",
				"FLRY3",
				"FLEX3",
				"FRAS3",
				"GFSA3",
				"GSHP3",
				"GGBR3",
				"GGBR4",
				"GOLL4",
				"GPIV33",
				"GPCP3",
				"GPCP4",
				"CGRA3",
				"CGRA4",
				"GRND3",
				"SOMA3",
				"CNTO3",
				"GUAR3",
				"HAGA3",
				"HAGA4",
				"HAPV3",
				"HBOR3",
				"HETA3",
				"HETA4",
				"HOOT3",
				"HOOT4",
				"HYPE3",
				"IGBR3",
				"IGSN3",
				"IGTA3",
				"JBDU3",
				"JBDU4",
				"ROMI3",
				"INEP3",
				"INEP4",
				"PARD3",
				"INNT3",
				"MEAL3",
				"FIGE3",
				"FIGE4",
				"MYPK3",
				"RANI3",
				"RANI4",
				"IRBR3",
				"ITUB3",
				"ITUB4",
				"ITSA3",
				"ITSA4",
				"JBSS3",
				"JPSA3",
				"JHSF3",
				"JFEN3",
				"JOPA3",
				"JOPA4",
				"JSLG3",
				"CTKA3",
				"CTKA4",
				"KEPL3",
				"KLBN11",
				"KLBN3",
				"KLBN4",
				"LMED3",
				"LIGT3",
				"LINX3",
				"RENT3",
				"LWSA3",
				"LOGG3",
				"LOGN3",
				"LAME3",
				"LAME4",
				"LJQQ3",
				"LREN3",
				"LPSB3",
				"LUPA3",
				"MDIA3",
				"MSRO3",
				"MGLU3",
				"LEVE3",
				"MGEL3",
				"MGEL4",
				"ESTR3",
				"ESTR4",
				"POMO3",
				"POMO4",
				"MRFG3",
				"AMAR3",
				"MERC3",
				"MERC4",
				"FRIO3",
				"MTIG3",
				"MTIG4",
				"GOAU3",
				"GOAU4",
				"RSUL3",
				"RSUL4",
				"MTSA3",
				"MTSA4",
				"MILS3",
				"MMAQ3",
				"MMAQ4",
				"BEEF3",
				"MNPR3",
				"MTRE3",
				"MMXM3",
				"MOAR3",
				"MDNE3",
				"MOVI3",
				"MRVE3",
				"MULT3",
				"MNDL3",
				"NTCO3",
				"NEOE3",
				"NORD3",
				"NRTQ3",
				"GNDI3",
				"ODPV3",
				"OIBR3",
				"OIBR4",
				"OMGE3",
				"OSXB3",
				"OFSA3",
				"PDTC3",
				"PATI3",
				"PATI4",
				"PMAM3",
				"PTBL3",
				"PDGR3",
				"PRIO3",
				"BRDT3",
				"PETR3",
				"PETR4",
				"PTNT3",
				"PTNT4",
				"PLAS3",
				"PPAR3",
				"FRTA3",
				"PSSA3",
				"POSI3",
				"PPLA11",
				"PTCA11",
				"PTCA3",
				"PRNR3",
				"PFRM3",
				"QUAL3",
				"QUSW3",
				"RADL3",
				"RAPT3",
				"RAPT4",
				"RCSL3",
				"RCSL4",
				"REDE3",
				"RPMG3",
				"RNEW11",
				"RNEW3",
				"RNEW4",
				"GEPA3",
				"GEPA4",
				"RDNI3",
				"RSID3",
				"RAIL3",
				"SNSY3",
				"SNSY5",
				"SNSY6",
				"STBP3",
				"SCAR3",
				"SMTO3",
				"AHEB3",
				"AHEB5",
				"AHEB6",
				"SLED3",
				"SLED4",
				"SHUL3",
				"SHUL4",
				"SEER3",
				"APTI3",
				"APTI4",
				"SQIA3",
				"SLCE3",
				"SMFT3",
				"SMLS3",
				"SOND3",
				"SOND5",
				"SOND6",
				"SPRI3",
				"SPRI5",
				"SPRI6",
				"SGPS3",
				"STTR3",
				"STKF3",
				"SULA11",
				"SULA3",
				"SULA4",
				"NEMO3",
				"NEMO5",
				"NEMO6",
				"SUZB3",
				"SHOW3",
				"TASA3",
				"TASA4",
				"TECN3",
				"TCSA3",
				"TCNO3",
				"TCNO4",
				"TGMA3",
				"TEKA3",
				"TEKA4",
				"TKNO3",
				"TKNO4",
				"TELB3",
				"TELB4",
				"VIVT3",
				"VIVT4",
				"TESA3",
				"TIMP3",
				"TOTS3",
				"TPIS3",
				"TAEE11",
				"TAEE3",
				"TAEE4",
				"LUXM3",
				"LUXM4",
				"TRIS3",
				"CRPG3",
				"CRPG5",
				"CRPG6",
				"TUPY3",
				"UGPA3",
				"UCAS3",
				"UNIP3",
				"UNIP5",
				"UNIP6",
				"USIM3",
				"USIM5",
				"USIM6",
				"VALE3",
				"VLID3",
				"VVAR3",
				"VIVA3",
				"VIVR3",
				"VULC3",
				"WEGE3",
				"MWET3",
				"MWET4",
				"WHRL3",
				"WHRL4",
				"WIZS3",
				"WLMM3",
				"WLMM4",
				"YDUQ3"
// ===================================================================================				
//				"ADHM3",
//				"ADHM3F",
//				"TIET11",
//				"TIET3",
//				"TIET3F",
//				"TIET4",
//				"TIET4F",
//				"AFLT3",
//				"AFLT3F",
//				"RPAD3",
//				"RPAD3F",
//				"RPAD5",
//				"RPAD5F",
//				"RPAD6",
//				"ALSO3",
//				"ALSO3F",
//				"ALPK3",
//				"ALPK3F",
//				"ALPA3",
//				"ALPA3F",
//				"ALPA4",
//				"ALPA4F",
//				"APER3",
//				"APER3F",
//				"ALUP11",
//				"ALUP3",
//				"ALUP3F",
//				"ALUP4",
//				"ALUP4F",
//				"ABEV3",
//				"ABEV3F",
//				"AMBP3",
//				"AMBP3F",
//				"CBEE3",
//				"CBEE3F",
//				"ANIM3",
//				"ANIM3F",
//				"ARZZ3",
//				"ARZZ3F",
//				"CRFB3",
//				"CRFB3F",
//				"ATOM3",
//				"ATOM3F",
//				"AZEV3",
//				"AZEV3F",
//				"AZEV4",
//				"AZEV4F",
//				"AZUL4",
//				"AZUL4F",
//				"BTOW3",
//				"BTOW3F",
//				"B3SA3",
//				"B3SA3F",
//				"BAHI3",
//				"BAHI3F",
//				"BMGB4",
//				"BMGB4F",
//				"BIDI11",
//				"BIDI3",
//				"BIDI3F",
//				"BIDI4",
//				"BIDI4F",
//				"BEES3",
//				"BEES3F",
//				"BEES4",
//				"BEES4F",
//				"BDLL3",
//				"BDLL3F",
//				"BDLL4",
//				"BDLL4F",
//				"BTTL3",
//				"BTTL3F",
//				"BALM3",
//				"BALM3F",
//				"BALM4",
//				"BALM4F",
//				"BBSE3",
//				"BBSE3F",
//				"BBML3",
//				"BBML3F",
//				"ABCB4",
//				"ABCB4F",
//				"BRIV3",
//				"BRIV3F",
//				"BRIV4",
//				"BRIV4F",
//				"BAZA3",
//				"BAZA3F",
//				"BBDC3",
//				"BBDC3F",
//				"BBDC4",
//				"BBDC4F",
//				"BBAS11",
//				"BBAS3",
//				"BBAS3F",
//				"BPAC11",
//				"BPAC3",
//				"BPAC3F",
//				"BPAC5",
//				"BPAC5F",
//				"BGIP3",
//				"BGIP3F",
//				"BGIP4",
//				"BGIP4F",
//				"BPAR3",
//				"BPAR3F",
//				"BRSR3",
//				"BRSR3F",
//				"BRSR5",
//				"BRSR5F",
//				"BRSR6",
//				"IDVL3",
//				"IDVL3F",
//				"IDVL4",
//				"IDVL4F",
//				"BMIN3",
//				"BMIN3F",
//				"BMIN4",
//				"BMIN4F",
//				"BMEB3",
//				"BMEB3F",
//				"BMEB4",
//				"BMEB4F",
//				"BNBR3",
//				"BNBR3F",
//				"BPAN4",
//				"BPAN4F",
//				"PINE3",
//				"PINE3F",
//				"PINE4",
//				"PINE4F",
//				"SANB11",
//				"SANB3",
//				"SANB3F",
//				"SANB4",
//				"SANB4F",
//				"BMKS3",
//				"BMKS3F",
//				"BIOM3",
//				"BIOM3F",
//				"BSEV3",
//				"BSEV3F",
//				"BKBR3",
//				"BKBR3F",
//				"BOBR3",
//				"BOBR3F",
//				"BOBR4",
//				"BOBR4F",
//				"BRML3",
//				"BRML3F",
//				"BRPR3",
//				"BRPR3F",
//				"BRAP3",
//				"BRAP3F",
//				"BRAP4",
//				"BRAP4F",
//				"BBRK3",
//				"BBRK3F",
//				"AGRO3",
//				"AGRO3F",
//				"BRKM3",
//				"BRKM3F",
//				"BRKM5",
//				"BRKM5F",
//				"BRKM6",
//				"BSLI3",
//				"BSLI3F",
//				"BSLI4",
//				"BSLI4F",
//				"BRFS3",
//				"BRFS3F",
//				"BRQB3",
//				"BRQB3F",
//				"CAMB3",
//				"CAMB3F",
//				"CAML3",
//				"CAML3F",
//				"CCRO3",
//				"CCRO3F",
//				"CEAB3",
//				"CEAB3F",
//				"MAPT3",
//				"MAPT3F",
//				"MAPT4",
//				"MAPT4F",
//				"ELET3",
//				"ELET3F",
//				"ELET5",
//				"ELET5F",
//				"ELET6",
//				"CLSC3",
//				"CLSC3F",
//				"CLSC4",
//				"CLSC4F",
//				"AALR3",
//				"AALR3F",
//				"CESP3",
//				"CESP3F",
//				"CESP5",
//				"CESP5F",
//				"CESP6",
//				"PCAR3",
//				"PCAR3F",
//				"CASN3",
//				"CASN3F",
//				"CASN4",
//				"CASN4F",
//				"GPAR3",
//				"GPAR3F",
//				"CEGR3",
//				"CEGR3F",
//				"CEEB3",
//				"CEEB3F",
//				"CEEB5",
//				"CEEB5F",
//				"CEEB6",
//				"CEBR3",
//				"CEBR3F",
//				"CEBR5",
//				"CEBR5F",
//				"CEBR6",
//				"CMIG3",
//				"CMIG3F",
//				"CMIG4",
//				"CMIG4F",
//				"CEPE3",
//				"CEPE3F",
//				"CEPE5",
//				"CEPE5F",
//				"CEPE6",
//				"COCE3",
//				"COCE3F",
//				"COCE5",
//				"COCE5F",
//				"COCE6",
//				"CSRN3",
//				"CSRN3F",
//				"CSRN5",
//				"CSRN5F",
//				"CSRN6",
//				"CEED3",
//				"CEED3F",
//				"CEED4",
//				"CEED4F",
//				"EEEL3",
//				"EEEL3F",
//				"EEEL4",
//				"EEEL4F",
//				"FESA3",
//				"FESA3F",
//				"FESA4",
//				"FESA4F",
//				"CEDO3",
//				"CEDO3F",
//				"CEDO4",
//				"CEDO4F",
//				"CGAS3",
//				"CGAS3F",
//				"CGAS5",
//				"CGAS5F",
//				"HBTS3",
//				"HBTS3F",
//				"HBTS5",
//				"HBTS5F",
//				"HBTS6",
//				"HGTX3",
//				"HGTX3F",
//				"CATA3",
//				"CATA3F",
//				"CATA4",
//				"CATA4F",
//				"LCAM3",
//				"LCAM3F",
//				"MSPA3",
//				"MSPA3F",
//				"MSPA4",
//				"MSPA4F",
//				"CPLE3",
//				"CPLE3F",
//				"CPLE5",
//				"CPLE5F",
//				"CPLE6",
//				"PEAB3",
//				"PEAB3F",
//				"PEAB4",
//				"PEAB4F",
//				"SBSP3",
//				"SBSP3F",
//				"CSMG3",
//				"CSMG3F",
//				"SAPR11",
//				"SAPR3",
//				"SAPR3F",
//				"SAPR4",
//				"SAPR4F",
//				"CSAB3",
//				"CSAB3F",
//				"CSAB4",
//				"CSAB4F",
//				"CSNA3",
//				"CSNA3F",
//				"CTNM3",
//				"CTNM3F",
//				"CTNM4",
//				"CTNM4F",
//				"CTSA3",
//				"CTSA3F",
//				"CTSA4",
//				"CTSA4F",
//				"CTSA8",
//				"CTSA8F",
//				"CIEL3",
//				"CIEL3F",
//				"CMSA3",
//				"CMSA3F",
//				"CMSA4",
//				"CMSA4F",
//				"CNSY3",
//				"CNSY3F",
//				"COGN3",
//				"COGN3F",
//				"ODER3",
//				"ODER3F",
//				"ODER4",
//				"ODER4F",
//				"BRGE11",
//				"BRGE3",
//				"BRGE3F",
//				"BRGE5",
//				"BRGE5F",
//				"BRGE6",
//				"BRGE7",
//				"BRGE7F",
//				"BRGE8",
//				"BRGE8F",
//				"CALI3",
//				"CALI3F",
//				"CALI4",
//				"CALI4F",
//				"TEND3",
//				"TEND3F",
//				"CORR3",
//				"CORR3F",
//				"CORR4",
//				"CORR4F",
//				"RLOG3",
//				"RLOG3F",
//				"CSAN3",
//				"CSAN3F",
//				"CPFE3",
//				"CPFE3F",
//				"CRDE3",
//				"CRDE3F",
//				"CARD3",
//				"CARD3F",
//				"CTCA3",
//				"CTCA3F",
//				"TRPL3",
//				"TRPL3F",
//				"TRPL4",
//				"TRPL4F",
//				"CVCB3",
//				"CVCB3F",
//				"CYRE3",
//				"CYRE3F",
//				"CCPR3",
//				"CCPR3F",
//				"DMVF3",
//				"DMVF3F",
//				"DASA3",
//				"DASA3F",
//				"PNVL3",
//				"PNVL3F",
//				"PNVL4",
//				"PNVL4F",
//				"DIRR3",
//				"DIRR3F",
//				"DOHL3",
//				"DOHL3F",
//				"DOHL4",
//				"DOHL4F",
//				"DMMO3",
//				"DMMO3F",
//				"DTCY3",
//				"DTCY3F",
//				"DTCY4",
//				"DTCY4F",
//				"DTEX3",
//				"DTEX3F",
//				"ECOR3",
//				"ECOR3F",
//				"ENBR3",
//				"ENBR3F",
//				"EALT3",
//				"EALT3F",
//				"EALT4",
//				"EALT4F",
//				"EKTR3",
//				"EKTR3F",
//				"EKTR4",
//				"EKTR4F",
//				"LIPR3",
//				"LIPR3F",
//				"EMAE3",
//				"EMAE3F",
//				"EMAE4",
//				"EMAE4F",
//				"EMBR3",
//				"EMBR3F",
//				"ECPR3",
//				"ECPR3F",
//				"ECPR4",
//				"ECPR4F",
//				"ENAT3",
//				"ENAT3F",
//				"ENMT3",
//				"ENMT3F",
//				"ENMT4",
//				"ENMT4F",
//				"ENGI11",
//				"ENGI3",
//				"ENGI3F",
//				"ENGI4",
//				"ENGI4F",
//				"ENEV3",
//				"ENEV3F",
//				"EGIE3",
//				"EGIE3F",
//				"EQTL3",
//				"EQTL3F",
//				"EQPA3",
//				"EQPA3F",
//				"EQPA5",
//				"EQPA5F",
//				"EQPA6",
//				"EQPA7",
//				"EQPA7F",
//				"ETER3",
//				"ETER3F",
//				"EUCA3",
//				"EUCA3F",
//				"EUCA4",
//				"EUCA4F",
//				"EVEN3",
//				"EVEN3F",
//				"BAUH3",
//				"BAUH3F",
//				"BAUH4",
//				"BAUH4F",
//				"EZTC3",
//				"EZTC3F",
//				"VSPT3",
//				"VSPT3F",
//				"VSPT4",
//				"VSPT4F",
//				"FHER3",
//				"FHER3F",
//				"CRIV3",
//				"CRIV3F",
//				"CRIV4",
//				"CRIV4F",
//				"FNCN3",
//				"FNCN3F",
//				"FLRY3",
//				"FLRY3F",
//				"FLEX3",
//				"FLEX3F",
//				"FRAS3",
//				"FRAS3F",
//				"GFSA3",
//				"GFSA3F",
//				"GSHP3",
//				"GSHP3F",
//				"GGBR3",
//				"GGBR3F",
//				"GGBR4",
//				"GGBR4F",
//				"GOLL4",
//				"GOLL4F",
//				"GPIV33",
//				"GPIV33F",
//				"GPCP3",
//				"GPCP3F",
//				"GPCP4",
//				"GPCP4F",
//				"CGRA3",
//				"CGRA3F",
//				"CGRA4",
//				"CGRA4F",
//				"GRND3",
//				"GRND3F",
//				"SOMA3",
//				"SOMA3F",
//				"CNTO3",
//				"CNTO3F",
//				"GUAR3",
//				"GUAR3F",
//				"HAGA3",
//				"HAGA3F",
//				"HAGA4",
//				"HAGA4F",
//				"HAPV3",
//				"HAPV3F",
//				"HBOR3",
//				"HBOR3F",
//				"HETA3",
//				"HETA3F",
//				"HETA4",
//				"HETA4F",
//				"HOOT3",
//				"HOOT3F",
//				"HOOT4",
//				"HOOT4F",
//				"HYPE3",
//				"HYPE3F",
//				"IGBR3",
//				"IGBR3F",
//				"IGSN3",
//				"IGSN3F",
//				"IGTA3",
//				"IGTA3F",
//				"JBDU3",
//				"JBDU3F",
//				"JBDU4",
//				"JBDU4F",
//				"ROMI3",
//				"ROMI3F",
//				"INEP3",
//				"INEP3F",
//				"INEP4",
//				"INEP4F",
//				"PARD3",
//				"PARD3F",
//				"INNT3",
//				"INNT3F",
//				"MEAL3",
//				"MEAL3F",
//				"FIGE3",
//				"FIGE3F",
//				"FIGE4",
//				"FIGE4F",
//				"MYPK3",
//				"MYPK3F",
//				"RANI3",
//				"RANI3F",
//				"RANI4",
//				"RANI4F",
//				"IRBR3",
//				"IRBR3F",
//				"ITUB3",
//				"ITUB3F",
//				"ITUB4",
//				"ITUB4F",
//				"ITSA3",
//				"ITSA3F",
//				"ITSA4",
//				"ITSA4F",
//				"JBSS3",
//				"JBSS3F",
//				"JPSA3",
//				"JPSA3F",
//				"JHSF3",
//				"JHSF3F",
//				"JFEN3",
//				"JFEN3F",
//				"JOPA3",
//				"JOPA3F",
//				"JOPA4",
//				"JOPA4F",
//				"JSLG3",
//				"JSLG3F",
//				"CTKA3",
//				"CTKA3F",
//				"CTKA4",
//				"CTKA4F",
//				"KEPL3",
//				"KEPL3F",
//				"KLBN11",
//				"KLBN3",
//				"KLBN3F",
//				"KLBN4",
//				"KLBN4F",
//				"LMED3",
//				"LMED3F",
//				"LIGT3",
//				"LIGT3F",
//				"LINX3",
//				"LINX3F",
//				"RENT3",
//				"RENT3F",
//				"LWSA3",
//				"LWSA3F",
//				"LOGG3",
//				"LOGG3F",
//				"LOGN3",
//				"LOGN3F",
//				"LAME3",
//				"LAME3F",
//				"LAME4",
//				"LAME4F",
//				"LJQQ3",
//				"LJQQ3F",
//				"LREN3",
//				"LREN3F",
//				"LPSB3",
//				"LPSB3F",
//				"LUPA3",
//				"LUPA3F",
//				"MDIA3",
//				"MDIA3F",
//				"MSRO3",
//				"MSRO3F",
//				"MGLU3",
//				"MGLU3F",
//				"LEVE3",
//				"LEVE3F",
//				"MGEL3",
//				"MGEL3F",
//				"MGEL4",
//				"MGEL4F",
//				"ESTR3",
//				"ESTR3F",
//				"ESTR4",
//				"ESTR4F",
//				"POMO3",
//				"POMO3F",
//				"POMO4",
//				"POMO4F",
//				"MRFG3",
//				"MRFG3F",
//				"AMAR3",
//				"AMAR3F",
//				"MERC3",
//				"MERC3F",
//				"MERC4",
//				"MERC4F",
//				"FRIO3",
//				"FRIO3F",
//				"MTIG3",
//				"MTIG3F",
//				"MTIG4",
//				"MTIG4F",
//				"GOAU3",
//				"GOAU3F",
//				"GOAU4",
//				"GOAU4F",
//				"RSUL3",
//				"RSUL3F",
//				"RSUL4",
//				"RSUL4F",
//				"MTSA3",
//				"MTSA3F",
//				"MTSA4",
//				"MTSA4F",
//				"MILS3",
//				"MILS3F",
//				"MMAQ3",
//				"MMAQ3F",
//				"MMAQ4",
//				"MMAQ4F",
//				"BEEF3",
//				"BEEF3F",
//				"MNPR3",
//				"MNPR3F",
//				"MTRE3",
//				"MTRE3F",
//				"MMXM3",
//				"MMXM3F",
//				"MOAR3",
//				"MOAR3F",
//				"MDNE3",
//				"MDNE3F",
//				"MOVI3",
//				"MOVI3F",
//				"MRVE3",
//				"MRVE3F",
//				"MULT3",
//				"MULT3F",
//				"MNDL3",
//				"MNDL3F",
//				"NTCO3",
//				"NTCO3F",
//				"NEOE3",
//				"NEOE3F",
//				"NORD3",
//				"NORD3F",
//				"NRTQ3",
//				"NRTQ3F",
//				"GNDI3",
//				"GNDI3F",
//				"ODPV3",
//				"ODPV3F",
//				"OIBR3",
//				"OIBR3F",
//				"OIBR4",
//				"OIBR4F",
//				"OMGE3",
//				"OMGE3F",
//				"OSXB3",
//				"OSXB3F",
//				"OFSA3",
//				"OFSA3F",
//				"PDTC3",
//				"PDTC3F",
//				"PATI3",
//				"PATI3F",
//				"PATI4",
//				"PATI4F",
//				"PMAM3",
//				"PMAM3F",
//				"PTBL3",
//				"PTBL3F",
//				"PDGR3",
//				"PDGR3F",
//				"PRIO3",
//				"PRIO3F",
//				"BRDT3",
//				"BRDT3F",
//				"PETR3",
//				"PETR3F",
//				"PETR4",
//				"PETR4F",
//				"PTNT3",
//				"PTNT3F",
//				"PTNT4",
//				"PTNT4F",
//				"PLAS3",
//				"PLAS3F",
//				"PPAR3",
//				"PPAR3F",
//				"FRTA3",
//				"FRTA3F",
//				"PSSA3",
//				"PSSA3F",
//				"POSI3",
//				"POSI3F",
//				"PPLA11",
//				"PTCA11",
//				"PTCA3",
//				"PTCA3F",
//				"PRNR3",
//				"PRNR3F",
//				"PFRM3",
//				"PFRM3F",
//				"QUAL3",
//				"QUAL3F",
//				"QUSW3",
//				"QUSW3F",
//				"RADL3",
//				"RADL3F",
//				"RAPT3",
//				"RAPT3F",
//				"RAPT4",
//				"RAPT4F",
//				"RCSL3",
//				"RCSL3F",
//				"RCSL4",
//				"RCSL4F",
//				"REDE3",
//				"REDE3F",
//				"RPMG3",
//				"RPMG3F",
//				"RNEW11",
//				"RNEW3",
//				"RNEW3F",
//				"RNEW4",
//				"RNEW4F",
//				"GEPA3",
//				"GEPA3F",
//				"GEPA4",
//				"GEPA4F",
//				"RDNI3",
//				"RDNI3F",
//				"RSID3",
//				"RSID3F",
//				"RAIL3",
//				"RAIL3F",
//				"SNSY3",
//				"SNSY3F",
//				"SNSY5",
//				"SNSY5F",
//				"SNSY6",
//				"STBP3",
//				"STBP3F",
//				"SCAR3",
//				"SCAR3F",
//				"SMTO3",
//				"SMTO3F",
//				"AHEB3",
//				"AHEB3F",
//				"AHEB5",
//				"AHEB5F",
//				"AHEB6",
//				"SLED3",
//				"SLED3F",
//				"SLED4",
//				"SLED4F",
//				"SHUL3",
//				"SHUL3F",
//				"SHUL4",
//				"SHUL4F",
//				"SEER3",
//				"SEER3F",
//				"APTI3",
//				"APTI3F",
//				"APTI4",
//				"APTI4F",
//				"SQIA3",
//				"SQIA3F",
//				"SLCE3",
//				"SLCE3F",
//				"SMFT3",
//				"SMFT3F",
//				"SMLS3",
//				"SMLS3F",
//				"SOND3",
//				"SOND3F",
//				"SOND5",
//				"SOND5F",
//				"SOND6",
//				"SPRI3",
//				"SPRI3F",
//				"SPRI5",
//				"SPRI5F",
//				"SPRI6",
//				"SGPS3",
//				"SGPS3F",
//				"STTR3",
//				"STTR3F",
//				"STKF3",
//				"STKF3F",
//				"SULA11",
//				"SULA3",
//				"SULA3F",
//				"SULA4",
//				"SULA4F",
//				"NEMO3",
//				"NEMO3F",
//				"NEMO5",
//				"NEMO5F",
//				"NEMO6",
//				"SUZB3",
//				"SUZB3F",
//				"SHOW3",
//				"SHOW3F",
//				"TASA3",
//				"TASA3F",
//				"TASA4",
//				"TASA4F",
//				"TECN3",
//				"TECN3F",
//				"TCSA3",
//				"TCSA3F",
//				"TCNO3",
//				"TCNO3F",
//				"TCNO4",
//				"TCNO4F",
//				"TGMA3",
//				"TGMA3F",
//				"TEKA3",
//				"TEKA3F",
//				"TEKA4",
//				"TEKA4F",
//				"TKNO3",
//				"TKNO3F",
//				"TKNO4",
//				"TKNO4F",
//				"TELB3",
//				"TELB3F",
//				"TELB4",
//				"TELB4F",
//				"VIVT3",
//				"VIVT3F",
//				"VIVT4",
//				"VIVT4F",
//				"TESA3",
//				"TESA3F",
//				"TIMP3",
//				"TIMP3F",
//				"TOTS3",
//				"TOTS3F",
//				"TPIS3",
//				"TPIS3F",
//				"TAEE11",
//				"TAEE3",
//				"TAEE3F",
//				"TAEE4",
//				"TAEE4F",
//				"LUXM3",
//				"LUXM3F",
//				"LUXM4",
//				"LUXM4F",
//				"TRIS3",
//				"TRIS3F",
//				"CRPG3",
//				"CRPG3F",
//				"CRPG5",
//				"CRPG5F",
//				"CRPG6",
//				"TUPY3",
//				"TUPY3F",
//				"UGPA3",
//				"UGPA3F",
//				"UCAS3",
//				"UCAS3F",
//				"UNIP3",
//				"UNIP3F",
//				"UNIP5",
//				"UNIP5F",
//				"UNIP6",
//				"USIM3",
//				"USIM3F",
//				"USIM5",
//				"USIM5F",
//				"USIM6",
//				"VALE3",
//				"VALE3F",
//				"VLID3",
//				"VLID3F",
//				"VVAR3",
//				"VVAR3F",
//				"VIVA3",
//				"VIVA3F",
//				"VIVR3",
//				"VIVR3F",
//				"VULC3",
//				"VULC3F",
//				"WEGE3",
//				"WEGE3F",
//				"MWET3",
//				"MWET3F",
//				"MWET4",
//				"MWET4F",
//				"WHRL3",
//				"WHRL3F",
//				"WHRL4",
//				"WHRL4F",
//				"WIZS3",
//				"WIZS3F",
//				"WLMM3",
//				"WLMM3F",
//				"WLMM4",
//				"WLMM4F",
//				"YDUQ3",
//				"YDUQ3F"
				);
//====================================================

		cot.downloadNegociosByStockUntilNow(codes, "11/09/2020");
	}
}